#!/usr/bin/env swift

//
//  GeneratePrefixAliases.swift
//  RyzeUI
//
//  Created by Rafael Escaleira on 09/04/26.
//
//  Script para gerar automaticamente typealiases com prefixo personalizado
//
//  Uso:
//  ```bash
//  swift Scripts/GeneratePrefixAliases.swift <PREFIX> <OUTPUT_PATH>
//  ```
//
//  Exemplo:
//  ```bash
//  swift Scripts/GeneratePrefixAliases.swift Zenith ./Sources/MyApp/ZenithAliases.swift
//  ```
//

import Foundation

// MARK: - Configuration

struct Configuration {
    let prefix: String
    let outputURL: URL
    let copyright: String
    let createdDate: String
    let creator: String

    init(prefix: String, outputURL: URL) {
        self.prefix = prefix
        self.outputURL = outputURL
        self.copyright = """
        //
        //  \(prefix)UIPrefixAliases.swift
        //  RyzeUI
        //
        //  Generated by GeneratePrefixAliases.swift
        //

        """
        self.createdDate = DateFormatter.localizedString(from: Date(), dateStyle: .medium, timeStyle: .none)
        self.creator = "RyzeUI Prefix Generator"
    }
}

// MARK: - Type Definition

struct TypeDefinition {
    let name: String
    let category: String

    static let allTypes: [TypeDefinition] = [
        // Atoms
        .init(name: "RyzeButton", category: "Atoms"),
        .init(name: "RyzeText", category: "Atoms"),
        .init(name: "RyzeTextField", category: "Atoms"),
        .init(name: "RyzeSymbol", category: "Atoms"),
        .init(name: "RyzeSpacer", category: "Atoms"),
        .init(name: "RyzeVStack", category: "Atoms"),
        .init(name: "RyzeHStack", category: "Atoms"),
        .init(name: "RyzeZStack", category: "Atoms"),
        .init(name: "RyzeLazyList", category: "Atoms"),
        .init(name: "RyzeList", category: "Atoms"),
        .init(name: "RyzeHorizontalList", category: "Atoms"),
        .init(name: "RyzeAsyncImage", category: "Atoms"),
        .init(name: "RyzeShape", category: "Atoms"),
        .init(name: "RyzeSection", category: "Atoms"),
        .init(name: "RyzeLabel", category: "Atoms"),
        .init(name: "RyzeTabView", category: "Atoms"),

        // Molecules
        .init(name: "RyzeTag", category: "Molecules"),
        .init(name: "RyzeCarousel", category: "Molecules"),
        .init(name: "RyzePrimaryButton", category: "Molecules"),
        .init(name: "RyzeSecondaryButton", category: "Molecules"),
        .init(name: "RyzeBodyText", category: "Molecules"),
        .init(name: "RyzeFootnoteText", category: "Molecules"),
        .init(name: "RyzeCurrencyTextField", category: "Molecules"),
        .init(name: "RyzeNavigationView", category: "Molecules"),
        .init(name: "RyzeBrowserView", category: "Molecules"),
        .init(name: "RyzeVideoView", category: "Molecules"),

        // Accessibility
        .init(name: "RyzeAccessibilityProperties", category: "Accessibility"),
        .init(name: "RyzeAccessibilityConfig", category: "Accessibility"),
        .init(name: "RyzeAccessibility", category: "Accessibility"),
        .init(name: "RyzeAccessibilityAction", category: "Accessibility"),
        .init(name: "RyzeAccessibilityBuilder", category: "Accessibility"),
        .init(name: "RyzeAccessibilityHint", category: "Accessibility"),

        // Styles & Tokens
        .init(name: "RyzeColor", category: "Styles & Tokens"),
        .init(name: "RyzeSpacing", category: "Styles & Tokens"),
        .init(name: "RyzeRadius", category: "Styles & Tokens"),
        .init(name: "RyzeSize", category: "Styles & Tokens"),
        .init(name: "RyzeGradient", category: "Styles & Tokens"),
        .init(name: "RyzeSemanticColors", category: "Styles & Tokens"),
        .init(name: "RyzeDesignTokens", category: "Styles & Tokens"),
        .init(name: "SpacingToken", category: "Styles & Tokens"),
        .init(name: "RadiusToken", category: "Styles & Tokens"),
        .init(name: "FontSizeToken", category: "Styles & Tokens"),
        .init(name: "MotionToken", category: "Styles & Tokens"),
        .init(name: "Breakpoint", category: "Styles & Tokens"),

        // Protocols
        .init(name: "RyzeThemeProtocol", category: "Protocols"),
        .init(name: "RyzeColorProtocol", category: "Protocols"),
        .init(name: "RyzeSpacingProtocol", category: "Protocols"),
        .init(name: "RyzeRadiusProtocol", category: "Protocols"),
        .init(name: "RyzeSizeProtocol", category: "Protocols"),
        .init(name: "RyzeFontProtocol", category: "Protocols"),
        .init(name: "RyzeFontFamilyProtocol", category: "Protocols"),
        .init(name: "RyzeTextFieldMask", category: "Protocols"),
        .init(name: "RyzeTextFieldConfiguration", category: "Protocols"),
        .init(name: "RyzeUIMock", category: "Protocols"),

        // Errors & Enums
        .init(name: "RyzeUIError", category: "Errors & Enums"),
        .init(name: "RyzeTextInputAutocapitalization", category: "Errors & Enums"),
        .init(name: "RyzeTextFieldContentType", category: "Errors & Enums"),
    ]
}

// MARK: - Generator

class AliasGenerator {
    private let config: Configuration

    init(config: Configuration) {
        self.config = config
    }

    func generate() -> String {
        var output = ""

        // Header
        output += "//\n"
        output += "//  \(config.prefix)UIPrefixAliases.swift\n"
        output += "//  RyzeUI\n"
        output += "//\n"
        output += "//  Generated by \(config.creator) on \(config.createdDate).\n"
        output += "//\n"
        output += "//  Arquivo de typealiases para personalização de prefixo do Design System.\n"
        output += "//  Este arquivo foi gerado automaticamente pelo script GeneratePrefixAliases.swift\n"
        output += "//\n"
        output += "//  PARA USAR: Importe este arquivo no seu projeto e use os aliases com prefixo '\(config.prefix)'\n"
        output += "//\n"
        output += "//  Exemplo:\n"
        output += "//  ```swift\n"
        output += "//  import RyzeUI\n"
        output += "//\n"
        output += "//  var button: \(config.prefix)Button\n"
        output += "//  var text: \(config.prefix)Text\n"
        output += "//  ```\n"
        output += "//\n"
        output += "\n"
        output += "import SwiftUI\n"
        output += "\n"

        // Group types by category
        let groupedTypes = Dictionary(grouping: TypeDefinition.allTypes) { $0.category }

        // Generate typealiases for each category
        for category in groupedTypes.keys.sorted() {
            let types = groupedTypes[category]!
            output += "// MARK: - \(category)\n"
            output += "\n"

            for type in types {
                let aliasName = type.name.replacingOccurrences(of: "Ryze", with: config.prefix)
                output += "public typealias \(aliasName) = \(type.name)\n"
            }

            output += "\n"
        }

        // View Modifiers Extensions
        output += "// MARK: - View Modifiers Extensions\n"
        output += "\n"
        output += "extension View {\n"
        output += "    // MARK: - Accessibility\n"
        output += "\n"
        output += "    /// Aplica prefixo personalizado às propriedades de acessibilidade\n"
        output += "    public func \(config.prefix.lowercased())(accessibility properties: RyzeAccessibilityProperties) -> some View {\n"
        output += "        ryze(accessibility: properties)\n"
        output += "    }\n"
        output += "\n"
        output += "    /// Atalho para definir apenas testID com prefixo personalizado\n"
        output += "    public func \(config.prefix.lowercased())(testID: String) -> some View {\n"
        output += "        ryze(testID: testID)\n"
        output += "    }\n"
        output += "\n"
        output += "    /// Aplica propriedades de acessibilidade usando builder pattern com prefixo personalizado\n"
        output += "    public func \(config.prefix.lowercased())(accessibility builder: (RyzeAccessibilityConfig) -> RyzeAccessibilityConfig) -> some View {\n"
        output += "        ryze(accessibility: builder)\n"
        output += "    }\n"
        output += "\n"
        output += "    // MARK: - Style Modifiers\n"
        output += "\n"
        output += "    /// Aplica cor de fundo com prefixo personalizado\n"
        output += "    public func \(config.prefix.lowercased())(background style: RyzeColor) -> some View {\n"
        output += "        ryze(background: style)\n"
        output += "    }\n"
        output += "\n"
        output += "    /// Aplica cor de tint com prefixo personalizado\n"
        output += "    public func \(config.prefix.lowercased())(tint color: RyzeColor) -> some View {\n"
        output += "        ryze(tint: color)\n"
        output += "    }\n"
        output += "\n"
        output += "    /// Aplica cor de foreground com prefixo personalizado\n"
        output += "    public func \(config.prefix.lowercased())(color: RyzeColor) -> some View {\n"
        output += "        ryze(color: color)\n"
        output += "    }\n"
        output += "\n"
        output += "    // MARK: - Environment Modifiers\n"
        output += "\n"
        output += "    /// Aplica tema com prefixo personalizado\n"
        output += "    public func \(config.prefix.lowercased())(theme: RyzeThemeProtocol) -> some View {\n"
        output += "        ryze(theme: theme)\n"
        output += "    }\n"
        output += "\n"
        output += "    /// Aplica locale com prefixo personalizado\n"
        output += "    public func \(config.prefix.lowercased())(locale: RyzeLocale) -> some View {\n"
        output += "        ryze(locale: locale)\n"
        output += "    }\n"
        output += "\n"
        output += "    /// Aplica color scheme com prefixo personalizado\n"
        output += "    public func \(config.prefix.lowercased())(colorScheme: ColorScheme? = nil) -> some View {\n"
        output += "        ryze(colorScheme: colorScheme)\n"
        output += "    }\n"
        output += "\n"
        output += "    /// Aplica estado de loading com prefixo personalizado\n"
        output += "    public func \(config.prefix.lowercased())(loading: Bool) -> some View {\n"
        output += "        ryze(loading: loading)\n"
        output += "    }\n"
        output += "\n"
        output += "    /// Aplica estado de disabled com prefixo personalizado\n"
        output += "    public func \(config.prefix.lowercased())(disabled: Bool) -> some View {\n"
        output += "        ryze(disabled: disabled)\n"
        output += "    }\n"
        output += "\n"
        output += "    // MARK: - Text Modifiers\n"
        output += "\n"
        output += "    /// Aplica alinhamento de texto com prefixo personalizado\n"
        output += "    public func \(config.prefix.lowercased())(alignment: TextAlignment) -> some View {\n"
        output += "        ryze(alignment: alignment)\n"
        output += "    }\n"
        output += "\n"
        output += "    /// Aplica fonte com prefixo personalizado\n"
        output += "    public func \(config.prefix.lowercased())(\n"
        output += "        font: Font = .body,\n"
        output += "        weight: Font.Weight? = nil,\n"
        output += "        design: Font.Design? = nil\n"
        output += "    ) -> some View {\n"
        output += "        ryze(font: font, weight: weight, design: design)\n"
        output += "    }\n"
        output += "\n"
        output += "    // MARK: - Size & Spacing Modifiers\n"
        output += "\n"
        output += "    /// Aplica tamanho com prefixo personalizado\n"
        output += "    public func \(config.prefix.lowercased())(\n"
        output += "        width: RyzeSize? = nil,\n"
        output += "        height: RyzeSize? = nil,\n"
        output += "        alignment: Alignment = .center\n"
        output += "    ) -> some View {\n"
        output += "        ryze(width: width, height: height, alignment: alignment)\n"
        output += "    }\n"
        output += "\n"
        output += "    /// Aplica padding com prefixo personalizado\n"
        output += "    public func \(config.prefix.lowercased())Padding(\n"
        output += "        _ edges: Edge.Set = .all,\n"
        output += "        _ spacing: RyzeSpacing = .medium\n"
        output += "    ) -> some View {\n"
        output += "        ryzePadding(edges, spacing)\n"
        output += "    }\n"
        output += "\n"
        output += "    /// Aplica padding com prefixo personalizado (todas as bordas)\n"
        output += "    public func \(config.prefix.lowercased())Padding(\n"
        output += "        _ spacing: RyzeSpacing = .medium\n"
        output += "    ) -> some View {\n"
        output += "        ryzePadding(spacing)\n"
        output += "    }\n"
        output += "\n"
        output += "    // MARK: - Background Modifiers\n"
        output += "\n"
        output += "    /// Aplica background padrão com prefixo personalizado\n"
        output += "    public func \(config.prefix.lowercased())Background() -> some View {\n"
        output += "        ryzeBackground()\n"
        output += "    }\n"
        output += "\n"
        output += "    /// Aplica background secundário com prefixo personalizado\n"
        output += "    public func \(config.prefix.lowercased())BackgroundSecondary() -> some View {\n"
        output += "        ryzeBackgroundSecondary()\n"
        output += "    }\n"
        output += "\n"
        output += "    /// Aplica background de row com prefixo personalizado\n"
        output += "    public func \(config.prefix.lowercased())BackgroundRow() -> some View {\n"
        output += "        ryzeBackgroundRow()\n"
        output += "    }\n"
        output += "\n"
        output += "    // MARK: - Effect Modifiers\n"
        output += "\n"
        output += "    /// Aplica efeito glow com prefixo personalizado\n"
        output += "    public func \(config.prefix.lowercased())Glow(for color: Color? = nil) -> some View {\n"
        output += "        ryzeGlow(for: color)\n"
        output += "    }\n"
        output += "\n"
        output += "    /// Aplica efeito de símbolo com prefixo personalizado\n"
        output += "    public func \(config.prefix.lowercased())Symbol<T: IndefiniteSymbolEffect & SymbolEffect>(\n"
        output += "        effect: T,\n"
        output += "        options: SymbolEffectOptions = .default,\n"
        output += "        isActive: Bool = true\n"
        output += "    ) -> some View {\n"
        output += "        ryzeSymbol(effect: effect, options: options, isActive: isActive)\n"
        output += "    }\n"
        output += "\n"
        output += "    /// Aplica efeito skeleton com prefixo personalizado\n"
        output += "    public func \(config.prefix.lowercased())Skeleton() -> some View {\n"
        output += "        ryzeSkeleton()\n"
        output += "    }\n"
        output += "\n"
        output += "    /// Aplica efeito parallax com prefixo personalizado (iOS apenas)\n"
        output += "    public func \(config.prefix.lowercased())Parallax(width: RyzeSize? = nil, height: RyzeSize?) -> some View {\n"
        output += "        ryzeParallax(width: width, height: height)\n"
        output += "    }\n"
        output += "\n"
        output += "    /// Aplica efeito de confetti com prefixo personalizado\n"
        output += "    public func \(config.prefix.lowercased())Confetti(\n"
        output += "        amount: Int = 30,\n"
        output += "        seconds: Int = 4,\n"
        output += "        isActive: Bool\n"
        output += "    ) -> some View {\n"
        output += "        ryzeConfetti(amount: amount, seconds: seconds, isActive: isActive)\n"
        output += "    }\n"
        output += "\n"
        output += "    // MARK: - Shape & Clip Modifiers\n"
        output += "\n"
        output += "    /// Aplica clip de shape com prefixo personalizado\n"
        output += "    public func \(config.prefix.lowercased())(clip shape: RyzeShape) -> some View {\n"
        output += "        ryze(clip: shape)\n"
        output += "    }\n"
        output += "\n"
        output += "    // MARK: - Screen & Display Modifiers\n"
        output += "\n"
        output += "    /// Aplica observação de screen com prefixo personalizado\n"
        output += "    public func \(config.prefix.lowercased())ScreenObserve(minimumWidthScreen: CGFloat = 430) -> some View {\n"
        output += "        ryzeScreenObserve(minimumWidthScreen: minimumWidthScreen)\n"
        output += "    }\n"
        output += "\n"
        output += "    /// Aplica browser sheet com prefixo personalizado\n"
        output += "    public func \(config.prefix.lowercased())Browser(url: Binding<URL?>) -> some View {\n"
        output += "        ryzeBrowser(url: url)\n"
        output += "    }\n"
        output += "\n"
        output += "    // MARK: - Preview Modifiers\n"
        output += "\n"
        output += "    /// Aplica preview com prefixo personalizado\n"
        output += "    public func \(config.prefix.lowercased())Preview(\n"
        output += "        layout: PreviewLayout,\n"
        output += "        orientation: InterfaceOrientation,\n"
        output += "        colorScheme: ColorScheme,\n"
        output += "        locale: RyzeLocale\n"
        output += "    ) -> some View {\n"
        output += "        ryzePreview(\n"
        output += "            layout: layout,\n"
        output += "            orientation: orientation,\n"
        output += "            colorScheme: colorScheme,\n"
        output += "            locale: locale\n"
        output += "        )\n"
        output += "    }\n"
        output += "\n"
        output += "    // MARK: - Conditional Modifiers\n"
        output += "\n"
        output += "    /// Aplica transformação condicional com prefixo personalizado\n"
        output += "    public func \(config.prefix.lowercased())<Content: View>(\n"
        output += "        if condition: Bool,\n"
        output += "        transition: AnyTransition = .scale,\n"
        output += "        animation: Animation? = .linear,\n"
        output += "        transform: (Self) -> Content\n"
        output += "    ) -> some View {\n"
        output += "        ryze(if: condition, transition: transition, animation: animation, transform: transform)\n"
        output += "    }\n"
        output += "\n"
        output += "    /// Aplica transformação condicional com item opcional\n"
        output += "    public func \(config.prefix.lowercased())<Content: View, Value>(\n"
        output += "        item value: Value?,\n"
        output += "        transform: (Self, Value) -> Content\n"
        output += "    ) -> some View {\n"
        output += "        ryze(item: value, transform: transform)\n"
        output += "    }\n"
        output += "\n"
        output += "    /// Aplica transformação condicional com else\n"
        output += "    public func \(config.prefix.lowercased())<Content: View, ElseContent: View>(\n"
        output += "        if condition: Bool,\n"
        output += "        transform: (Self) -> Content,\n"
        output += "        `else`: ((Self) -> ElseContent)? = nil\n"
        output += "    ) -> some View {\n"
        output += "        ryze(if: condition, transform: transform, else: `else`)\n"
        output += "    }\n"
        output += "\n"
        output += "    /// Aplica transformação condicional com item opcional e else\n"
        output += "    public func \(config.prefix.lowercased())<Content: View, Value, ElseContent: View>(\n"
        output += "        item value: Value?,\n"
        output += "        transform: (Self, Value) -> Content,\n"
        output += "        `else`: ((Self) -> ElseContent)? = nil\n"
        output += "    ) -> some View {\n"
        output += "        ryze(item: value, transform: transform, else: `else`)\n"
        output += "    }\n"
        output += "}\n"

        return output
    }

    func write() throws {
        let directory = config.outputURL.deletingLastPathComponent()
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)

        let content = generate()
        try content.write(to: config.outputURL, atomically: true, encoding: .utf8)

        print("✅ Arquivo gerado com sucesso: \(config.outputURL.path)")
        print("📊 Total de typealiases: \(TypeDefinition.allTypes.count)")
    }
}

// MARK: - Main

func main() {
    let arguments = CommandLine.arguments

    guard arguments.count >= 2 else {
        print("❌ Uso: swift GeneratePrefixAliases.swift <PREFIX> [OUTPUT_PATH]")
        print("")
        print("Exemplos:")
        print("  swift GeneratePrefixAliases.swift Zenith")
        print("  swift GeneratePrefixAliases.swift App ./MyApp/Aliases/AppPrefixAliases.swift")
        print("")
        print("O arquivo será gerado em:")
        print("  ./Sources/RyzeUI/Exports/<PREFIX>UIPrefixAliases.swift (padrão)")
        exit(1)
    }

    let prefix = arguments[1]
    let outputPath: String

    if arguments.count >= 3 {
        outputPath = arguments[2]
    } else {
        // Caminho relativo ao diretório atual
        outputPath = "./\(prefix)UIPrefixAliases.swift"
    }

    let outputURL = URL(fileURLWithPath: outputPath)

    print("🚀 Gerando typealiases com prefixo '\(prefix)'...")
    print("📁 Output: \(outputURL.path)")
    print("")

    let config = Configuration(prefix: prefix, outputURL: outputURL)
    let generator = AliasGenerator(config: config)

    do {
        try generator.write()
    } catch {
        print("❌ Erro ao gerar arquivo: \(error)")
        exit(1)
    }
}

main()
